// Auto-generated by scripts/prebuild-comics.js — do not edit

export interface ComicContentEntry {
  title: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  category: string;
  excerpt: string;
  content: string;
}

export const comicContentReleased: Record<string, ComicContentEntry> = {
};