// Auto-generated by scripts/prebuild-comics.js — do not edit
// Only comics with releaseDate <= COMIC_RELEASE_AS_OF (or today) are included.

export interface ComicPostEntry {
  slug: string;
  title: string;
  excerpt: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  category: string;
  featured: boolean;
  image: string;
}

export const comicPostsReleased: ComicPostEntry[] = [
];

export const comicReleaseAsOf = "2025-01-01";
export const comicReleasedCount = 0;