#!/usr/bin/env node
/**
 * Prebuild: Generate released-comic modules for blog + copy released images
 *
 * Runs before `next build`. Reads COMIC_EPISODES_DATA.json, filters to
 * episodes with releaseDate <= COMIC_RELEASE_AS_OF (or today), and:
 * 1. Writes app/blog/comic-posts-generated.ts and comic-content-generated.ts
 * 2. Copies only released episode images from private/images/comics/ to public/images/comics/
 *
 * SECURITY: Images in private/ are never accessible via URL. Only released episodes
 * get their images copied to public/ at build time. No security by obscurity.
 *
 * Usage:
 *   node scripts/prebuild-comics.js
 *   COMIC_RELEASE_AS_OF=2026-02-06 node scripts/prebuild-comics.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const EPISODES_PATH = path.join(ROOT, 'docs', 'COMIC_EPISODES_DATA.json');
const OUT_POSTS = path.join(ROOT, 'app', 'blog', 'comic-posts-generated.ts');
const OUT_CONTENT = path.join(ROOT, 'app', 'blog', 'comic-content-generated.ts');

const asOf = process.env.COMIC_RELEASE_AS_OF || new Date().toISOString().slice(0, 10);

const raw = JSON.parse(fs.readFileSync(EPISODES_PATH, 'utf-8'));
const episodes = raw.episodes || [];
const series = raw.seriesInfo || {};

const released = episodes.filter((ep) => ep.releaseDate && ep.releaseDate <= asOf);

function tsEscape(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function formatDate(ymd) {
  const [y, m, d] = ymd.split('-').map(Number);
  const date = new Date(y, m - 1, d);
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

const postsLines = [
  '// Auto-generated by scripts/prebuild-comics.js — do not edit',
  '// Only comics with releaseDate <= COMIC_RELEASE_AS_OF (or today) are included.',
  '',
  'export interface ComicPostEntry {',
  '  slug: string;',
  '  title: string;',
  '  excerpt: string;',
  '  author: string;',
  '  authorRole: string;',
  '  date: string;',
  '  readTime: string;',
  '  category: string;',
  '  featured: boolean;',
  '  image: string;',
  '}',
  '',
  'export const comicPostsReleased: ComicPostEntry[] = [',
];

for (const ep of released) {
  const title = `The Gateway: Episode ${ep.number} - ${ep.title}`;
  const excerpt = `${ep.linkedinHook || ''} See how Alex and Jordan protect everyone silently.`;
  const date = formatDate(ep.releaseDate);
  const image = `/images/comics/comic-episode-${String(ep.number).padStart(2, '0')}.png`;
  postsLines.push('  {');
  postsLines.push(`    slug: ${JSON.stringify(ep.slug)},`);
  postsLines.push(`    title: ${JSON.stringify(title)},`);
  postsLines.push(`    excerpt: ${JSON.stringify(excerpt)},`);
  postsLines.push(`    author: 'The Gateway Team',`);
  postsLines.push(`    authorRole: 'Office Comedy',`);
  postsLines.push(`    date: ${JSON.stringify(date)},`);
  postsLines.push(`    readTime: '1 min read',`);
  postsLines.push(`    category: 'Comics',`);
  postsLines.push(`    featured: ${ep.number <= 3},`);
  postsLines.push(`    image: ${JSON.stringify(image)},`);
  postsLines.push('  },');
}
postsLines.push('];');
postsLines.push('');
postsLines.push(`export const comicReleaseAsOf = ${JSON.stringify(asOf)};`);
postsLines.push(`export const comicReleasedCount = ${released.length};`);

fs.writeFileSync(OUT_POSTS, postsLines.join('\n'));

const contentLines = [
  '// Auto-generated by scripts/prebuild-comics.js — do not edit',
  '',
  'export interface ComicContentEntry {',
  '  title: string;',
  '  author: string;',
  '  authorRole: string;',
  '  date: string;',
  '  readTime: string;',
  '  category: string;',
  '  excerpt: string;',
  '  content: string;',
  '}',
  '',
  'export const comicContentReleased: Record<string, ComicContentEntry> = {',
];

for (const ep of released) {
  const title = `The Gateway: Episode ${ep.number} - ${ep.title}`;
  const excerpt = `${ep.linkedinHook || ''} See how Alex and Jordan protect everyone silently.`;
  const date = formatDate(ep.releaseDate);
  const imgPath = `/images/comics/comic-episode-${String(ep.number).padStart(2, '0')}.png`;
  const content = [
    `# ${title}`,
    '',
    `**${ep.theme || ''}**`,
    '',
    "It's Thursday. Here's what happened at the office this week.",
    '',
    `![The Gateway Episode ${ep.number}](${imgPath})`,
    '',
    ep.linkedinHook || '',
    '',
    'Alex and Jordan protect everyone silently. No drama. No speeches. Just quiet heroism.',
    '',
    '---',
    '',
    '## About "The Gateway"',
    '',
    '"The Gateway" is a weekly comic series about two engineers who protect their entire organization from AI data leaks. Every Thursday, we share a new episode showing how ZeroShare Gateway blocks PII and secrets automatically.',
    '',
    '**Previous episodes:** [View all comics](/blog?category=Comics)',
    '',
    '**Next episode:** Coming next Thursday',
  ].join('\n');
  contentLines.push(`  [${JSON.stringify(ep.slug)}]: {`);
  contentLines.push(`    title: ${JSON.stringify(title)},`);
  contentLines.push(`    author: 'The Gateway Team',`);
  contentLines.push(`    authorRole: 'Office Comedy',`);
  contentLines.push(`    date: ${JSON.stringify(date)},`);
  contentLines.push(`    readTime: '1 min read',`);
  contentLines.push(`    category: 'Comics',`);
  contentLines.push(`    excerpt: ${JSON.stringify(excerpt)},`);
  contentLines.push(`    content: ${JSON.stringify(content)},`);
  contentLines.push('  },');
}
contentLines.push('};');

fs.writeFileSync(OUT_CONTENT, contentLines.join('\n'));

// SECURE IMAGE COPYING: Only released episodes get images copied to public/
const PRIVATE_IMAGES = path.join(ROOT, 'private', 'images', 'comics');
const PUBLIC_IMAGES = path.join(ROOT, 'public', 'images', 'comics');

// Ensure public directory exists
if (!fs.existsSync(PUBLIC_IMAGES)) {
  fs.mkdirSync(PUBLIC_IMAGES, { recursive: true });
}

// Clear existing public comic images (to remove any previously released that shouldn't be there)
const existingPublic = fs.readdirSync(PUBLIC_IMAGES).filter(f => f.startsWith('comic-episode-'));
for (const file of existingPublic) {
  fs.unlinkSync(path.join(PUBLIC_IMAGES, file));
}

// Copy only released episode images from private to public
let imagesCopied = 0;
for (const ep of released) {
  const num = String(ep.number).padStart(2, '0');
  const variants = [`comic-episode-${num}.png`, `comic-episode-${num}-linkedin.png`];
  
  for (const filename of variants) {
    const src = path.join(PRIVATE_IMAGES, filename);
    const dst = path.join(PUBLIC_IMAGES, filename);
    
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dst);
      imagesCopied++;
    }
  }
}

console.log(`prebuild-comics: COMIC_RELEASE_AS_OF=${asOf} → ${released.length} released`);
console.log(`  → ${OUT_POSTS}`);
console.log(`  → ${OUT_CONTENT}`);
console.log(`  → ${imagesCopied} images copied to public/`);
